project_id = "bvvzmprtuzdvvosaenbs"

[functions.submit-stress-questionnaire]
verify_jwt = false

[functions.submit-masterclass-registration]
verify_jwt = false

[functions.submit-program-registration]
verify_jwt = false

[functions.submit-calculator]
verify_jwt = false

[functions.submit-scientific-report]
verify_jwt = false

[functions.keep-alive]
verify_jwt = false
