// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvvzmprtuzdvvosaenbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2dnptcHJ0dXpkdnZvc2FlbmJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNjQ1NzUsImV4cCI6MjA2Njk0MDU3NX0.rj9abnsDxw4HbNGiL3gpSyJrQI1h-5GLiikrVW_1t0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});